import Head from "next/head";
import Link from "next/link";
import { useRouter, useSyncNextLocale } from "@hooks";
// import { useTranslation } from "next-i18next";
import type { NextPage } from "next";
import { Link as ChakraLink } from "@chakra-ui/react";
import { ROUTES } from "@api";
import { useEffect } from "react";

export const About: NextPage = () => {
  // const { t } = useTranslation(["common"]);
  const { locale } = useRouter();

  useSyncNextLocale(locale === "en" ? ROUTES.about.ro : ROUTES.about.en);

  // TODO add about structure and layout
  return (
    <div>
      <Head>
        {/* <title>{`GA studio - ${t("about")}`}</title> */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href={ROUTES.home}>
          about
          {/* <ChakraLink>{t("home")}</ChakraLink> */}
        </Link>
        {/* <h1>TODO: Implement {t("about")}</h1> */}
      </main>
    </div>
  );
};
