import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Container, Heading, Text } from "@chakra-ui/react";
import { useTestHook } from "@shared/hooks";
import { ProjectEntity } from "@/models";
import { getProjectBySlug } from "@/api";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    getProjectBySlug({
      slug: "primul-proiect",
      params: {
        populate: {
          content: {
            populate: "*",
          },
        },
      },
    }).then((d) => console.log(d.attributes));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text>Hello</Text>
    </>
  );
}
