import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Container, Heading, Text } from "@chakra-ui/react";
import { ProjectEntity } from "@models";
import { getProjectBySlug, ROUTES } from "@api";
import { useEffect } from "react";
import Link from "next/link";
import { useRouter } from "@shared/hooks";

type HomeProps = {
  data: ProjectEntity[];
};

export function Home({ data }: HomeProps) {
  // useEffect(() => {
  //   getProjectBySlug({
  //     slug: "primul-proiect",
  //     params: {
  //       populate: {
  //         content: {
  //           populate: "*",
  //         },
  //       },
  //     },
  //   }).then((d) => console.log(d.attributes));
  // }, []);
  const { locale } = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data.map(({ attributes }) => {
        const { title, slug } = attributes || {};

        if (!slug) return null;
        return (
          <Link key={slug} href={ROUTES.project[locale](slug)}>
            {title}
          </Link>
        );
      })}
    </>
  );
}
