import Head from "next/head";
import { HomePageEntity, UploadFileEntity } from "@models";
import { ROUTES } from "@api";
import { useSyncNextLocale } from "@shared/hooks";
import {
  Box,
  Center,
  HStack,
  List,
  ListItem,
  Stack,
  Text,
  VStack,
} from "@chakra-ui/react";

export type SectionProps = {
  imageData: UploadFileEntity;
};

import {
  HeroSection,
  ProcessSection,
  ServicesSection,
  VisionSection,
  ProjectsSection,
} from "./components";
import { TestimonialSection } from "./components/TestimonialSection";

type HomeProps = {
  homePage: HomePageEntity;
  categories: unknown[];
};

export function Home({ homePage }: HomeProps) {
  useSyncNextLocale(ROUTES.home);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection data={homePage.attributes!.hero} />

      <VisionSection data={homePage.attributes!.vision} />

      <ProcessSection data={homePage.attributes!.process} />

      <ServicesSection data={homePage.attributes!.service} />

      <ProjectsSection data={homePage.attributes!.projects} />

      <TestimonialSection data={homePage.attributes!.testimonials} />
    </>
  );
}
