import Head from "next/head";
import { HomePageEntity, UploadFileEntity } from "@models";
import { ROUTES } from "@api";
import { useSyncNextLocale } from "@shared/hooks";

export type SectionProps = {
  imageData: UploadFileEntity;
};

import {
  HeroSection,
  ProcessSection,
  ServicesSection,
  VisionSection,
  ProjectsSection,
} from "./components";
import { TestimonialSection } from "./components/TestimonialSection";

type HomeProps = {
  data: HomePageEntity;
};

export function Home({ data }: HomeProps) {
  useSyncNextLocale(ROUTES.home);

  const { hero, vision, process, service, projects, testimonials } =
    data.attributes ?? {};

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {hero && <HeroSection data={hero} />}

      {vision && <VisionSection data={vision} />}

      {process && <ProcessSection data={process} />}

      {service && <ServicesSection data={service} />}

      {projects && <ProjectsSection data={projects} />}

      {testimonials && Boolean(testimonials.testimonials?.data?.length) && (
        <TestimonialSection data={testimonials} />
      )}
    </>
  );
}
